enable-magisk-update = false

patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko Patches"

#[twitter]
#build-mode = "apk"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
#included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link'"


#[twitter-non-monet]
#build-mode = "apk"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
#included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link'"
#excluded-patches = "'Dynamic color'"

[x]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link'"

#[x-non-monet]
#build-mode = "apk"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
#included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link'"
#excluded-patches = "'Dynamic color'"
